### ISSUE TITLE
Missing emoji color variants of ☝️ and ✌️

### ISSUE THREAD

**Issue by guoyunhe** [googlefonts/noto-emoji#265]
![image](https://user-images.githubusercontent.com/5836790/60754952-76c3f800-9ff1-11e9-8d14-66b9a2d5af2b.png)

**Comment by dougfelt** [comment]
what platform are you viewing this on?

**Comment by guoyunhe** [comment]
@dougfelt Linux (openSUSE Tumbleweed) with Chromium. webpage https://eosrei.github.io/emojione-color-font/full-demo.html

**Comment by polarathene** [comment]
I can confirm this with Firefox 69 and Chrome 77 with Linux on Manjaro KDE(latest).

I've not yet adjusted my fontconfig to ensure "Noto Color Emoji" is prioritized. The "eosrei" site assigns the font-family "EmojiOne Color" followed by sans-serif. While getemoji.com assigns "Segoe UI Emoji".

## Chrome

In my case quite a few of the other hand glyphs surrounding the problem ones @guoyunhe is referencing are vertical rectangle pairs(wrong fallback font selected for initial or both parts?), some emoji render(fallback to Noto Color Emoji successfully), and these two ( ☝️🏻 , ✌️🏻 ) render a black/white outline(from Noto Sans Symbols2) which seems to be taking priority over Noto Color Emoji, I guess it matches the first glyph but fails with the 2nd pair? I get a square with the skin tone similar to @guoyunhe  picture, just the intended glyph is rendered differently(different font).

Chrome - eosrei original:
![eosrei_default_chrome](https://user-images.githubusercontent.com/5098581/65812712-533ed100-e21f-11e9-9af0-d7d828c902fd.png)

On Chrome viewing getemoji.com, these two emoji are also rendered as vertical rectangle pair outlines, assigning the font-family from eosrei did not reproduce the split graphic seen on that site.

Chrome - getemoji - No tone original:
![getemoji_default_chrome](https://user-images.githubusercontent.com/5098581/65812725-90a35e80-e21f-11e9-96f4-e9c6d8a25e04.png)

Chrome - getemoji - Light tone original:
![getemoji_light_default_chrome](https://user-images.githubusercontent.com/5098581/65812751-db24db00-e21f-11e9-940f-9da08399c6a2.png)

Setting the font-family to "Noto Color Emoji" fixes all the vertical rectangle pair glyph errors to show the proper emoji rendered for getemoji.com, on eosrei, it looks like @guoyunhe has shown above. 

Chrome - getemoji - No Tone **fixed**:
![getemoji_fixed_chrome](https://user-images.githubusercontent.com/5098581/65812783-62724e80-e220-11e9-8224-7fd8b376a750.png)

Chrome - getemoji - Light tone **fixed**:
![getemoji_light_fixed_chrome](https://user-images.githubusercontent.com/5098581/65812772-3bb41800-e220-11e9-8f38-0e32f52dc8f7.png)

Chrome - eosrei **fixed**:
![eosrei_kinda_fixed_chrome](https://user-images.githubusercontent.com/5098581/65812800-b4b36f80-e220-11e9-837b-df6430eba100.png)

## Firefox

On Firefox however, the eosrei rendering issue @guoyunhe shows is not there and it's fixed completely by assigning the "Noto Color Emoji" font. Firefox is however rendering the finger glyphs with "DejaVu Sans", instead of "Noto Sans Symbols2" prior to changing the font. 

I had gone into `about:config` for Firefox to swap the emoji font from "Mozilla Twemoji" that it ships with to "Noto Color Emoji"(prior to all this); So perhaps it's something to do with that, or each browsers fallback defaults?

Firefox - eosrei original (failed glyphs are being prioritized by DejaVu Sans - exact same for no tone emoji):
![eosrei_default_firefox](https://user-images.githubusercontent.com/5098581/65812833-4f13b300-e221-11e9-9c7b-37a8cdb82224.png)

Firefox - eosrei **fixed** (with Noto Color Emoji enforced as font-family in CSS):
![eosrei_fixed_firefox](https://user-images.githubusercontent.com/5098581/65812871-900bc780-e221-11e9-9817-af66cd972bd6.png)

Firefox - getemoji - No tone original:
![getemoji_default_firefox](https://user-images.githubusercontent.com/5098581/65812937-5c7d6d00-e222-11e9-812f-f7fb1d9101c0.png)

Firefox - getemoji - Light tone original:
![getemoji_light_default_firefox](https://user-images.githubusercontent.com/5098581/65812959-b7af5f80-e222-11e9-9cd3-52e3ec657934.png)

Firefox - getemoji - Light tone **fixed**:
![getemoji_light_fixed_firefox](https://user-images.githubusercontent.com/5098581/65813047-8b481300-e223-11e9-9fa3-ce3d671fad52.png)

No tone was omitted for fixed version since it had no issues in Firefox on getemoji here. Not sure what's up with the weird spacing/gaps in Firefox after applying the font. Interestingly both of the problem emoji identified by @guoyunhe are preceded by the whitespace/gaps. Without the fix, alignment was visibly off(especially noticeable with emoji on the right side), if comparison of such helps:

Firefox - getemoji - No tone **fixed**:
![getemoji_fixed_firefox](https://user-images.githubusercontent.com/5098581/65813088-6c964c00-e224-11e9-87e6-c971f921e6f8.png)

**Comment by polarathene** [comment]
The spacing/layout issue with Firefox appears to be due to how certain glyphs are rendering as "default", as in if you view the html text content, or copy/paste the emoji to any other field in the OS(not just within the web browser), where the content would not use the "Noto Color Emoji" and thus present 2 or more characters/glyphs in the text field.

Probably the same reason the spaces between the emoji are so much smaller compared to Chrome when using "Noto Color Emoji" where a space appears to be a full emoji width wide.

So that's more of a bug in Firefox doing the layout before calculating the final combined glyph width I guess?

**Comment by polarathene** [comment]
[Firefox bug reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1584718)

Appears my earlier assumption was wrong about being due to fontconfig messing with layout. It's either the [FE0H(Variation Selector-16)](https://emojipedia.org/variation-selector-16/) or [ZWJ](https://emojipedia.org/zero-width-joiner/) codepoints messing with the width of space characters. Bit weird since it seems to affect getemoji.com , but not the eosrei site.

**Comment by polarathene** [comment]
It's due to how the emoji were formatted in the HTML element. getemoji used a new line for each, where eosrei has no new lines. eosrei actually has emoji seperated with spaces, so the firefox bug is inserting spaces of emoji width for some reason on getemoji(but even if you manually add the spaces into the html, the `white-space: normal`(default) property in CSS is collapsing those(it keeps a single space if there's two characters between them on the same line(in the html text, not rendered element).

**Comment by polarathene** [comment]
I've found time to setup a custom font-config to resolve my rendering inconsistency/priority for emoji on Linux. Just looked into this mentioned bug report to see if it renders correctly.

**This report can be closed**. It's not a bug with the font, the reason for the issue is related to the source code. See the unmaintained repo with affected line in HTML [here](https://github.com/eosrei/emojione-color-font/blob/master/full-demo.html#L57). 

`☝️🏻` == `&#x270C&#xFE0F&#x1F3FB` vs `✌🏻` == `&#x270C&#x1F3FB`. It's been input incorrectly with the invisible/zero-width codepoint VS15(FE0F), which should not be inbetween the two codepoints(while it renders as 2 separate glyphs, it is treated as a single character). This was a developer error/bug in that projects codebase, they needed to properly combine the two codepoints for the [correct emoji/codepoint sequence](https://emojipedia.org/victory-hand-type-1-2/).

There does appear to be a bug in Chrome with rendering the skintone emoji/modifier in text content if it's not preceded by an emoji earlier, or the first in the element. The font fallback does not appear to work otherwise, the modifier also binds itself to the preceding character(including a space) which makes it treated as two characters like described above. I assume because that's how it's intended to be used with other emoji for modifying? Firefox behaves in a similar way, it renders correctly but still has a similar issue as described with binding and text handling.

**Comment by guoyunhe** [comment]
https://unicode.org/Public/emoji/12.0/emoji-test.txt

It is the Unicode standard:

```
270C FE0F                                  ; fully-qualified     # ✌️ victory hand
270C                                       ; unqualified         # ✌ victory hand
270C 1F3FB                                 ; fully-qualified     # ✌🏻 victory hand: light skin tone
270C 1F3FC                                 ; fully-qualified     # ✌🏼 victory hand: medium-light skin tone
270C 1F3FD                                 ; fully-qualified     # ✌🏽 victory hand: medium skin tone
270C 1F3FE                                 ; fully-qualified     # ✌🏾 victory hand: medium-dark skin tone
270C 1F3FF                                 ; fully-qualified     # ✌🏿 victory hand: dark skin tone
```

![image](https://user-images.githubusercontent.com/5836790/66322997-c20ce000-e92b-11e9-9e91-8e87e3356031.png)

**Comment by polarathene** [comment]
Yes, and when you render it with the codepoints like that, it works just fine with the "Noto Color Emoji" font:

![works_for_me](https://user-images.githubusercontent.com/5098581/66327021-923ef600-e986-11e9-92fa-611696f0954e.png)

Are you using Firefox? That has a bug I've linked you to earlier. The earlier eosrei site you linked to with a screenshot does not render a valid sequence, I explained that in my last post. It might not have rendered properly for you to make sense though, here you go:

![last_post](https://user-images.githubusercontent.com/5098581/66327845-fd3cfc80-e987-11e9-93a7-5c5946b19d32.png)

The eosrei emoji site is incorrectly encoded as `270C FE0F 1F3FB`, the VS16 should not be inbetween the two. How does it look on Chrome for you on getemoji.com or the unicode reference you linked?

It looks like you have DejaVu Sans taking priority for some of your glyphs(most of the victory hand emoji) in your screenshot. Your emoticons must be rendering in black/white then?

**Comment by dougfelt** [comment]
At the end of section 2.4 of [TR51](http://unicode.org/reports/tr51/#Presentation_Style) it reads:

> To have an effect on an emoji, an emoji modifier must immediately follow that base emoji character. Emoji presentation selectors are neither needed nor recommended for emoji characters when they are followed by emoji modifiers, and should not be used in newly generated emoji modifier sequences; the emoji modifier automatically implies the emoji presentation style. See ED-13. emoji modifier sequence. However, some older data may include defective emoji modifier sequences in which an emoji presentation selector does occur between the base emoji character and the emoji modifier; this is the only exception to the rule that an emoji modifier must immediately follow the character that it modifies. In this case the emoji presentation selector should be ignored.

Technically this sequence should be accepted by renderers, though it is invalid, because some legacy data might contain it.

**Comment by tomasdev** [comment]
The current version of the font includes these properly.
