### ISSUE TITLE
Serious Error on Mac OS Big Sur 11.2.1 barring install

### ISSUE THREAD

**Issue by adamlogan** [googlefonts/noto-emoji#332]
When attempting to install in Font Book on Mac oS Big Sur 11.2.1 I get the following prompt and I cannot install the color noto-emoji font.

<img width="622" alt="2021021217280649" src="https://user-images.githubusercontent.com/831586/107838776-3cd5de80-6d5c-11eb-9580-04bf9b1bd5d7.png">

**Comment by RoelN** [comment]
Looks like this error is triggered because of the absence of the `glyf` table. This is the same reason Windows refused to install the font. 

For now, please use [NotoColorEmoji_WindowsCompatible.ttf](https://github.com/googlefonts/noto-emoji/blob/master/fonts/NotoColorEmoji_WindowsCompatible.ttf), which will properly install on Big Sur.
