### ISSUE TITLE
Islamic Emirate of Afghanistan 

### ISSUE THREAD

**Issue by RandomErrorMessage** [googlefonts/noto-emoji#384]
The Islamic Republic of Afghanistan no longer exists and the sovereign country of Afghanistan is now governed by the Islamic Emirate of Afghanistan. The AF emoji should be updated to accurately represent the countries actual flag, such as how Wikipedia represents the flag: https://en.wikipedia.org/wiki/Afghanistan

**Comment by tomasdev** [comment]
I believe the request needs to be done to the Unicode Consortium first?

**Comment by RandomErrorMessage** [comment]
I do not believe this is the case. This is not a request for a new emoji, or even a real change of the unicode. This is just a flag update. Users have been warned for nearly a year that the AF flag will likely be updated to reflect the new flag: https://blog.emojipedia.org/what-about-the-afghanistan-flag-emoji/

**Comment by roozbehp** [comment]
I think it's premature to change the emoji flag when not a single country has recognized the Taliban government yet.

**Comment by RandomErrorMessage** [comment]
@roozbehp that is not true, several countries formally recognize the Taliban government and even those who do not as a matter of political posturing engage in formal diplomatic relations with the Taliban: https://en.wikipedia.org/wiki/Recognition_of_the_Islamic_Emirate_of_Afghanistan#2021%E2%80%93present

I'd rather not get into the semantic discussion of what constitutes as "formal recognition". It is easy to believe that - for example - the US will never recognize Islamic Emirate of Afghanistan while simultaneously treating them as the legitimate government in every other capacity.

**Comment by tim78245** [comment]
> I think it's premature to change the emoji flag when not a single country has recognized the Taliban government yet.

Why?

Unicode states:

> Some region sequences represent countries (as recognized by the United Nations, for example); others represent territories that are associated with a country. Such territories may have flags of their own, or may use the flag of the country with which they are associated. Depictions of images for flags may be subject to constraints by the administration of that region.

https://unicode.org/reports/tr51/

Unicode does not require a region's government must be recognized ("for example"). In fact the minimum definition seems only that it be an "administration."

The Republic of China is only recognized by 13 countries and is not a member of the UN, would you recommend representing the region of Taiwan with the flag of the Qing Dynasty? No? Then why represent the region of Afghanistan with an administration that similarly no longer exists?

**Comment by HinTak** [comment]
FWIW, it depends on what exactly the definition of that unicode code point is, or what it will be refined to ne (needing a mew proposal). Much of the CJK extention C D E F G's are historical/scholarly CJK variants not used in the last few hundred years. It is probably entirely reasonable to keep the old code point for the historical/old flag, and assign a new code point for a new flag, in a new unicode spec revision.

**Comment by RandomErrorMessage** [comment]
> Why?

We all know why. Some countries are merely more sovereign that others, and it's just so happens that this sovereign government wasn't installed by the CIA. I guess that means western megacorps will refuse to acknowledge your flag?

**Comment by tim78245** [comment]
> FWIW, it depends on what exactly the definition of that unicode code point is, or what it will be refined to be (needing a new proposal). Much of the CJK extention C D E F G's are historical/scholarly CJK variants not used in the last few hundred years. It is probably entirely reasonable to keep the old code point for the historical/old flag, and assign a new code point for a new flag, in a new unicode spec revision.

This has already been answered by Unicode:

> What about flags that change designs for geopolitical reasons?
> Unicode does not specify the appearance of flag emoji. It is the responsibility of font designers to update their fonts as politics change. EG: no Unicode changes required for https://emojipedia.org/flag-mauritania/

http://blog.unicode.org/2022/03/the-past-and-future-of-flag-emoji.html

Your suggestion is like saying Google Search should not update any search results of sites with a top level domain of .ly after the fall of the Great Socialist People's Libyan Arab Jamahiriya in 2011 because the State of Libya should really get it's own new top level domain (this would actually be more correct since there are already historic top level domains like .su). I mean whatever merits the idea has is not only irrelevant to the issue but also hits pause as reality moves on.

I would also like to make note that because the spec is about regions and not governments the font developer (Google in this case) does not have to use the flag of the Islamic Emirate of Afghanistan, even though in my view that would be the most consistent thing to do. What Google could do instead is use a simple place holder flag (as they do for their non-color Emoji flags), like a white flag with the letters AFG (perhaps in Arab script since that's what Afghan's use) until the time comes when the Islamic Emirate of Afghanistan is recognized by Google's government or the Islamic Emirate of Afghanistan ceases to exist (whichever comes first). This would also allow for a transitional period rather than shocking users at once at a flag change.

The Islamic Republic of Afghanistan no longer exists, it's not even representing Afghans in exile, it's flag should no longer represent the region of Afghanistan.

**Comment by folsze** [comment]
> I think it's premature to change the emoji flag when not a single country has recognized the Taliban government yet.

Counterargument:
I think it should simply be consistent with what Wikipedia displays. Why did Wikipedia change it then, if it's premature? And why would emojis not change it if Wikipedia did?

Or do you think the effort required for emojis is so significantly high, compared to uploading a Wikipedia image? I don't think it can be that hard

**Comment by m4rc1e** [comment]
> Or do you think the effort required for emojis is so significantly high, compared to uploading a Wikipedia image? I don't think it can be that hard

It's unfortunately damn hard. Changing the design is pretty straight forward. However, the sign off and QA it needs to go through afterwards is a lot of work.

**Comment by rsheeter** [comment]
Policy is we do not accept flags updates by PR so this cannot be accepted.
