### ISSUE TITLE
.

### ISSUE THREAD

**Issue by curya** [googlefonts/noto-emoji#424]
.

**Comment by rsheeter** [comment]
I don't believe this is something we can fix; Adobe would need to support the format we use for color emoji (https://developer.chrome.com/blog/colrv1-fonts/).

**Comment by curya** [comment]
@rsheeter Is that what the top one is? COLRv1?

**Comment by rsheeter** [comment]
It's possible we include fairly nasty xml in that one. Or ... @anthrotype does this seem potentially related to the subsetting issue you were poking at?

**Comment by anthrotype** [comment]
@curya in the screenshot you show two fonts, and then you say "the bottom one does work." 
Where did you get the two fonts from exactly? We need to know to be able to inspect them and try to reproduce.

> does this seem potentially related to the subsetting issue you were poking at?

**Comment by anthrotype** [comment]
> does this seem potentially related to the subsetting issue you were poking at?

you mean https://github.com/google/fonts/issues/6295 ? Maybe..

**Comment by anthrotype** [comment]
I don't think it's the subsetting issue because I tried downloading the font from fonts.google.com and it looks ok in Safari (which also uses the OT-SVT table inside this hybrid COLRv1+SVG noto emoji font).
I don't have Photoshop available to test this unfortunately. It might be that the OT-SVG table that nanoemoji produces is too complicated for Photoshop, as nanoemoji tries to share elements between SVG glyphs and to do that it has to merge them into single svg documents in the SVG table.
I believe the second font from @curya screenshot (which they say 'works') is the version of Noto Emoji that Adobe produced with their own tooling, https://github.com/adobe-fonts/noto-emoji-svg; that one has one glyph per svg document and thus no reuse or sharing of elements between different glyphs. Despite no reuse, their font's SVG table is actually 3 MB smaller than the one we make with nanoemoji, maybe they have optimized the svgs more aggressively (our picosvg makes SVG simpler to parse, not necessarily more compact).

**Comment by anthrotype** [comment]
oh, their SVG table is 3 MB smaller mostly because they use SVGz (zip compressed) variant, whereas we keep it uncompressed since it yields better result when it is converted to WOFF2

**Comment by anthrotype** [comment]
@curya I made a version of the Noto Color Emoji font that has a simplified SVG table (with one color glyph per svg document, and no sharing of elements across glyphs) like the Adobe one. Can you please test if this works in Photoshop?
You'll find it inside this zip archive:
[Noto-OTSVG.ttf.zip](https://github.com/googlefonts/noto-emoji/files/11575563/Noto-OTSVG.ttf.zip)

Please let us know, thank you!

**Comment by curya** [comment]
@anthrotype So I literally just deleted my installed Noto Emoji fonts but before I tried installing your version I started up Photoshop to make sure the fonts were really gone. And for some reason, Photoshop still shows them as existing. I can even type emojis with them. Not sure if I have to do a full restart or if this weird version of Noto Emoji somehow comes bundled with Photoshop...

**Comment by anthrotype** [comment]
> version of Noto Emoji somehow comes bundled with Photoshop...

hm maybe it does come bundled. We could ask our friends at Adobe to confirm /cc @miguelsousa 

In any case, the font I sent you early on should have a different family name, "Noto Color Emoji", whereas the one from Adobe I think they named it "Noto Color Emoji SVG"

**Comment by curya** [comment]
Ok. I installed yours and see no difference. Either I have to restart or the alleged bundled version is taking priority. The "empty" top font is still in the font list.

**Comment by anthrotype** [comment]
I think the top one is the font from Google Fonts (named "Noto Color Emoji Regular"), whereas the second one (which you said it works) is the bundled font from Adobe ("Noto Color Emoji SVG"):

![image](https://github.com/googlefonts/noto-emoji/assets/6939968/58174029-2a8f-43fd-adfa-4a96fba93f8e)

> I installed yours and see no difference. 

that's a pity

> Either I have to restart 

please try :)

> or the alleged bundled version is taking priority.

that's unlikely, they have different names so they count as two distinct fonts

**Comment by curya** [comment]
I don't even see a "Noto Color Emoji" in the list. Only the two in my previous screenshot.

**Comment by curya** [comment]
I *do* see "Noto Color Emoji Regular" in Illustrator though and that seems to work just fine minus the fact that the glyphs table takes like 10 seconds to load and also seems to be a little messed up:

![image](https://github.com/googlefonts/noto-emoji/assets/71131343/7deea9e5-3c95-404e-8394-a15913e0de08)
![image](https://github.com/googlefonts/noto-emoji/assets/71131343/84a5881a-4174-4adc-b0c5-4c74da135e8f)

**Comment by anthrotype** [comment]
ok so it works in Illustrator, good.
It takes time to load because it's huge big font, and it has to parse loads of SVGs.
The fact that you see all those glyph "parts" in the Illustrator Glyph Window is because the COLRv1 glyphs are composed using outlines from the glyf table (where regular black & white glyphs are also stored in non-color fonts). The font you download from the fonts.google.com zip file (as well as the custom one I uploaded here) is a hybrid font that contains both COLR and SVG tables; COLR table is used in Chrome, FireFox, Android, etc. wheres SVG table is used in Safari and Adobe desktop apps.

**Comment by HydroHydro** [comment]
Alright. I'll have to report back later about Photoshop since I'm in the middle of some work right now. But thank you for the help so far!

**Comment by curya** [comment]
Alright. I'll have to report back later on Photoshop since I'm in the middle of some work right now. But thank you for your help so far!

**Comment by anthrotype** [comment]
thanks Miguel! Do you know if Photoshop has any known issues with OT-SVG fonts? Does it use different font rendering stack from Illustrator?

**Comment by rsheeter** [comment]
> If the goal of including an SVG table in the COLRv1 fonts we serve is to increase compatibility and the one-glyph-per-svg-no-reuse variant has greater compatibility, then I would argue we should go for that one. I also think that parsing and rendering the "dumb" SVG table may be quicker (but have no metrics to support this theory).

I think you are right. The original implementation with shape sharing, etc was built to allow a fair comparison of binary size. In that context we ofc do want reuse. We're now using them for compatibility and, as you say, in that context we probably want the simple (no reuse, aka "dumb") model.

Maybe max color should support both options, with simple on by default?
