### ISSUE TITLE
Build other Emoji fonts besides Noto

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-emoji#9]
The `noto-emoji` project is two things at the same time:
- an open-source toolchain for converting SVG assets to TrueType with colored emoji glyphs;
- freely licensed SVG assets for the Noto Emoji glyphs.

After a few minor changes, our toolchain could also consume other free assets and generate optimized fonts for [Twitter Emoji](https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone) ([repo](https://github.com/twitter/twemoji), [license](https://github.com/twitter/twemoji/blob/gh-pages/LICENSE-GRAPHICS)) and [Emoji One](http://emojione.com/) ([repo](https://github.com/Ranks/emojione), [license](https://github.com/Ranks/emojione/blob/master/LICENSE.md)).

**Comment by behdad** [comment]
Yes, this should be easy.  We should probably move the building blocks into https://github.com/googlei18n/color-emoji and noto-emoji will be just one user.

**Comment by bmintz** [comment]
:+1:

**Comment by s40king** [comment]
👍

**Comment by thinkrick** [comment]
Hey guys,

This is the founder of Emoji One, and we've (internally) finished our upcoming emoji set which features every active unicode font codepoint.  Every emoji available by Apple (IOS 9.1) is now ready including skin tones and all.  We have a private github currently if any developers would like to get a head start, and it'll officially go live on our web-site on Dec 17th:  http://www.emojione.com

We'd love to have an official android font ready to go for this launch, and my tech is already looking into this.  If we can be of any help to noto-emoji, we'd love to be involved!  E-mail us at support@emojione.com, thanks.  :)

Regards,
Rick

**Comment by behdad** [comment]
Humm, how do people think we should do this?

**Comment by davelab6** [comment]
I discussed this with @thinkrick offline and its possible we could include the font in www.google.com/fonts/earlyaccess

**Comment by behdad** [comment]
> I discussed this with @thinkrick offline and its possible we could include the font in www.google.com/fonts/earlyaccess

That would be great!

**Comment by kq01526** [comment]
@davelab6 and @behdad and @thinkrick :

Do you have enough influence to make Android change it's Emoji set from the Google Noto Color Emoji set to the Emoji One Emoji set?

No offense, but the Emoji One Emoji set looks so much better than the Google Noto Color Emoji set. And so many people are agreeing on that. Just have a look at the comments in the following two issues on the AOSP issue tracker for example:

https://code.google.com/p/android/issues/detail?id=69755
https://code.google.com/p/android/issues/detail?id=73248

With the update to Android 6.0.1, Android got some additional Emojis, but unfortunately they still look as bad as before.

Is there any chance you guys could do something about this?

If Android would use the Emoji One Emoji set that would be so awesome!

The Emoji One Emoji set even is a better fit for the Material Design and it is visually a lot more compatible to the Apple set, which would make for a much better interoperability between those operating systems.

OR could you at least make switching the Emoji font possible on Android without having to be root?

Regards

**Comment by dougfelt** [comment]
> Do you have enough influence to make Android change it's Emoji set from the Google Noto Color Emoji set to the Emoji One Emoji set?

No, we don't.

**Comment by behdad** [comment]
CC @roozbehp @raphlinus

**Comment by roozbehp** [comment]
@behdad, do you guys need an action from me or Raph here?

**Comment by behdad** [comment]
> @behdad, do you guys need an action from me or Raph here?

@roozbehp no, was just FYI.

**Comment by kq01526** [comment]
> roozbehp@ wrote:
> 
> @behdad, do you guys need an action from me or Raph here?

Yes @roozbehp , we need an action from you or @raphlinus here (assuming you two are responsible for the Emoji font in Android).

Could you please please use the Emoji One font from @thinkrick in Android instead of Noto Color Emoji?

I think we can all agree that Emoji One simply is better than Noto Color Emoji.

Seriously, the majority of people would agree, please just have a look at the comments in the following two issues on the AOSP issue tracker for example:

https://code.google.com/p/android/issues/detail?id=69755
https://code.google.com/p/android/issues/detail?id=73248

Emoji One even provides a Android font now, see:

https://github.com/Ranks/emojione/tree/master/assets/fonts

I remember when Hiroshi Lockheimer was announcing new Emojis for Android 6.0.1 via Twitter:

https://twitter.com/lockheimer/status/672206241003937792

At first I thought now we're finally getting proper Material Design Emojis... but then... it was just additional Emojis for Noto Color Emoji, which do not go well with Material Design at all and look so ugly (sorry, no offense, but it's the truth).

Seriously, can someone please Cc Matías Duarte and Hiroshi Lockheimer on this?

Emoji One would be so much better for Android!

The Emoji One Emoji set even is a better fit for the Material Design and it is visually a lot more compatible to the Apple set, which would make for a much better interoperability between those operating systems.

Please, could you please please do it and please do it soon (ideally Android 6.0.2 or at least Android 7.0.0)?

Regards

**Comment by emunicio** [comment]
Indeed. I am experiencing problems with Android Emojis in 4.1.2. I am not using the google apps, so all my emojis looks black and white, and even a lot of them are missing (white spaces). It would be nice have all emojis, I am not saying that they have to be beautiful, but at least that they are all present

kind regards

**Comment by dougfelt** [comment]
Again, we don't control the design of the emoji set used for android.

Yes, we intend to provide color versions of the missing emoji codepoints.

We do intend to cover in B/W all emoji that have a B/W presentation.

It is possible to use the tooling to build a color emoji font with different resources.  You need .png image files named according to our convention, and to point the Makefile at them.  It is a bit cumbersome since some decisions (e.g., aliases of flags for some regions) are not configurable from the makefile, they're baked into code so you'd need to edit these.  I would like to clean the build code up but I'm not sure when I'll get to that, making it more configurable is one of the things I'd like to do.

**Comment by kq01526** [comment]
> @dougfelt wrote:
> 
> Again, we don't control the design of the emoji set used for android.

Could you please investigate who is in control of the design of the Emoji set used for Android and let us know and Cc him or her on that issue?

Please. Even Microsoft has better Material Design Emojis than Google now, see this Twitter post from today:

https://twitter.com/Emojipedia/status/717835593749630976

Sorry, this really is no offense, but Noto Color Emoji makes using Android less nice. With the Emoji One set or an entirely redesigned Emoji set from Google which would go well with Material Design and would provide better interoperability with the Apple set, Android would be so much better.

Please, it would be really nice if you could point this issue to the correct person and give us an update.

Could you do this please?

Regards

**Comment by dougfelt** [comment]
@kq01526 
Some final comments:

- Yes, some people do not like the current emoji set.  The people in charge know this already.

- Manufacturers of Android phones and products are free to use other emoji if they wish, and some do.  This site just provides tools to build an emoji font, and default resources for building it.

- This is not the right forum to raise such complaints.  Even if it were, this is bug is not about the look of the emoji, so it would be the wrong place to post these comments.

**Comment by dougfelt** [comment]
There are people who don't like the current emoji set.  The folks in charge know this.  

The emoji you see on your phone is not even necessarily the emoji on this site, manufacturers of Android products are free to use other emoji sets if they wish, and some do.

This is not the place to ask for a redesign.  This is not even the right bug on which to ask for a redesign, even if this were the right place.

**Comment by kq01526** [comment]
> @dougfelt wrote:
> 
> There are people who don't like the current emoji set. 

Yes, most people.

> The folks in charge know this. 

Then why don't they do anything about it?

> The emoji you see on your phone is not even necessarily the emoji on this site

Yes, I know that HTC, Samsung and LG have their own Emoji set, which are ugly as well IMHO.

> manufacturers of Android products are free to use other emoji sets if they wish, and some do.

Yes, but actual Android users are not. Not without rooting their devices.

> This is not the place to ask for a redesign.

Then what is the place to ask for a redesign if not this official Google repository for Noto Emojis?

Regards

**Comment by behdad** [comment]
@kq01526 You are being annoying now.  Doug said all that could be said and he made it clear those are his final comments.

**Comment by Crissov** [comment]
@eosrei has made [scfbuild](https://github.com/eosrei/scfbuild) to generate OTF fonts from [Emojione](https://github.com/eosrei/emojione-color-font) and [Twemoji](https://github.com/eosrei/twemoji-color-font). Its goal seems to be the same as described in the first bullet point in the OP by @brawer.

**Comment by eosrei** [comment]
Yes and no. ;) scfbuild currently only builds SVG-in-OpenType format color fonts. I have plans and received requests to build CBDT(what's used here) and SBIX, but haven't had the time to implement yet.

**Comment by rsheeter** [comment]
Closing as stale. I expect generic emoji font build tooling to emerge from the https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md effort.
